"""
RAG query engine.

Pipeline:
  1. Embed the student question via OpenAI text-embedding-3-small
  2. Retrieve top-K chunks from the tutor ChromaDB collection
  3. Build a mode-specific system prompt with the retrieved context
  4. Call GPT-4o-mini and return the response + source citations + confidence
     + optional visual_intent (concept description for DALL-E 3)

Visual Intent Decision Layer
----------------------------
The LLM is instructed to evaluate whether a diagram/visual would
significantly aid understanding.  If yes it embeds a JSON block:

    <<<VISUAL_INTENT>>>
    {"visual_prompt_description": "Labeled diagram of ..."}
    <<<END_VISUAL_INTENT>>>

This block is stripped from the visible response text before returning.
"""

import json
import logging
import re
from typing import List, Optional, Tuple

from app.core.config import settings

logger = logging.getLogger(__name__)

_VISUAL_INTENT_BLOCK_RE = re.compile(
    r"<<<VISUAL_INTENT>>>\s*(.*?)\s*<<<END[_ ]?VISUAL_INTENT>>>",
    re.DOTALL,
)

# Keywords that signal a student wants a visual aid
_VISUAL_KEYWORDS = {
    "show me", "draw", "diagram", "chart", "graph", "flowchart",
    "illustrate", "picture", "visualise", "visualize", "map",
    "sketch", "figure", "infographic", "image",
}

_VISUAL_INTENT_INSTRUCTION = """
--- VISUAL DIAGRAM GENERATION (separate from class materials) ---
IMPORTANT: The diagram is NOT fetched from the class materials.
It will be freshly GENERATED by an image AI (DALL-E 3) based on your description.
You do NOT need images to exist in the documents — you only need to describe the concept.

Emit the <<<VISUAL_INTENT>>> block if EITHER condition is true:
  A. The student explicitly asked for a diagram, drawing, chart, figure, or visual.
  B. The topic is inherently spatial/process-based (e.g. anatomy, circuits, flowcharts,
     molecular structures, timelines, graphs, maps) AND a diagram would give a clear
     mental model that text alone cannot efficiently provide.

When emitting, append EXACTLY the block below at the very end of your text reply.
Copy the delimiters character-for-character — do NOT add spaces inside <<< >>>.
Fill <description> with a dense, specific academic concept description:

<<<VISUAL_INTENT>>>
{"visual_prompt_description": "<description>"}
<<<END_VISUAL_INTENT>>>

Examples of good descriptions:
- "Labeled diagram of the human heart showing four chambers, valves, and blood flow direction"
- "C# object-oriented programming concept map showing classes, inheritance, interfaces, and polymorphism with arrows"
- "Flowchart of the water cycle showing evaporation, condensation, precipitation, and collection"

If neither condition is met, do NOT include the block.
--- END VISUAL DIAGRAM GENERATION ---
"""


def _embed_query(query):
    api_key = settings.OPENAI_API_KEY
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set in .env.")
    import openai
    client = openai.OpenAI(api_key=api_key)
    resp = client.embeddings.create(model="text-embedding-3-small", input=[query])
    return resp.data[0].embedding


def _call_llm(system_prompt, messages):
    api_key = settings.OPENAI_API_KEY
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set in .env.")
    import openai
    client = openai.OpenAI(api_key=api_key)
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "system", "content": system_prompt}] + messages,
        max_tokens=1800,
        temperature=0.4,
    )
    return resp.choices[0].message.content or ""


def _compute_confidence(distances):
    relevant = [d for d in distances if d < 1.4]
    if len(relevant) >= 3:
        return "high"
    if len(relevant) >= 1:
        return "medium"
    return "low"


def _student_wants_visual(message: str) -> bool:
    lower = message.lower()
    return any(kw in lower for kw in _VISUAL_KEYWORDS)


def _extract_visual_intent(raw_text: str):
    """Strip the VISUAL_INTENT block from the response and return (clean_text, description | None)."""
    match = _VISUAL_INTENT_BLOCK_RE.search(raw_text)
    if not match:
        return raw_text, None
    clean = _VISUAL_INTENT_BLOCK_RE.sub("", raw_text).strip()
    try:
        data = json.loads(match.group(1))
        description = data.get("visual_prompt_description") or None
    except (json.JSONDecodeError, AttributeError):
        description = None
    return clean, description


def run_rag_query(
    tutor_id,
    student_message,
    mode,
    history,
    custom_system_prompt=None,
    difficulty="intermediate",
    personality="supportive",
    teaching_style="detailed",
    tone="friendly",
    emphasis_topics=None,
):
    from app.services.ai_tutor import vector_index_manager as vim
    from app.services.ai_tutor.mode_prompts import build_system_prompt

    # 1. Embed query
    query_embedding = _embed_query(student_message)

    # 2. Retrieve context chunks
    docs, metas, distances = vim.query_collection(tutor_id, query_embedding, n_results=6)

    context_parts = []
    sources = []
    for i, (doc_text, meta, dist) in enumerate(zip(docs, metas, distances)):
        if dist > 1.4:
            continue
        context_parts.append(f"[Source {i + 1}]:\n{doc_text}")
        sources.append({
            "document_id":   int(meta["document_id"])   if meta.get("document_id")   else None,
            "transcript_id": int(meta["transcript_id"]) if meta.get("transcript_id") else None,
            "filename":      meta.get("filename", "Class material"),
            "doc_type":      meta.get("doc_type", "unknown"),
            "chunk_text":    doc_text[:200],
            "chunk_index":   int(meta.get("chunk_index", 0)),
        })

    context_text = (
        "\n\n".join(context_parts)
        if context_parts
        else "No specific class materials were found for this query."
    )

    # 3. Compute confidence
    confidence = _compute_confidence(distances)

    # 4. Build system prompt with all modifiers
    system_prompt = build_system_prompt(
        mode=mode,
        custom_system_prompt=custom_system_prompt,
        personality=personality,
        teaching_style=teaching_style,
        tone=tone,
        difficulty=difficulty,
        emphasis_topics=emphasis_topics,
    )
    system_prompt += (
        "--- CLASS MATERIALS CONTEXT ---\n"
        f"{context_text}\n"
        "--- END CONTEXT ---\n\n"
        "Ground your TEXT answer in the class materials above. "
        "If the materials don't cover the topic, say so honestly. "
        "The diagram generation rule below is INDEPENDENT of the class materials — "
        "always follow it based on what the student asked.\n\n"
    )
    system_prompt += _VISUAL_INTENT_INSTRUCTION

    # 5. Build LLM message history (last 10 turns)
    recent = history[-10:] if len(history) > 10 else history
    llm_messages = recent + [{"role": "user", "content": student_message}]

    # 6. Generate response
    raw_text = _call_llm(system_prompt, llm_messages)

    # 7. Extract optional visual intent block
    response_text, visual_intent = _extract_visual_intent(raw_text)

    return response_text, sources, confidence, visual_intent
